### ISSUE TITLE
rename folder 'master-schemas'

### ISSUE THREAD

**Issue by wilko77** [data61/clkhash#131]
Currently the schema specifications are stored in a folder named `master-schemas`.
We should rename that folder to `schema-specifications` to make purpose more obvious.

Don't forget to change the link to github in the `schema.rst` file in the docs.

Aha! Link: https://csiro.aha.io/features/ANONLINK-34

**Comment by nbgl** [comment]
If the folder name is not clear, then perhaps we should change ‘master schema’ everywhere in the code for future maintainability? (This could be as simple a command-F for ‘master’.)

**Comment by hardbyte** [comment]
Folder has been `schemas` for a while.

**Comment by nbgl** [comment]
I’ve had regrets about the name ‘master schema’ for a while. I think ‘metaschema’ would have been better…
