### ISSUE TITLE
n-grams of different identifier map to the same bits

### ISSUE THREAD

**Issue by wilko77** [data61/clkhash#19]
("John", "Doe") maps to the same bloom filter as ("Doe", "John"), because we always use the same set of _k_ hash functions for each identifier.

Schnell et.al. propose to use a different set of hash function for each identifier. 

Defining _d_ different sets of secrets for _d_ identifier seems tedious.

My proposal is to use a key derivation function to generate the necessary amount of secrets seeded by just one master secret.

Both, Java and Python standard library contain support for _PBKDF2WithHmacSHA1_.

**Comment by hardbyte** [comment]
The upstream bug has now been addressed - https://github.com/pyca/cryptography/pull/4037
