### ISSUE TITLE
Remove Appveyor and add Azure build status branch protection

### ISSUE THREAD

**Issue by gusmith** [data61/clkhash#268]
Currently, a commit can be merged if it  receives the appveyor build status `continuous-integration/appveyor/pr`.
But we are not replacing appveyor with Azure Build pipeline (merged in master with PR #262), so we should change the branch protection and change the appveyor configuration not to build the project anymore.

**Comment by hardbyte** [comment]
I've added the Azure checks and removed the requirement for appveyor:

![image](https://user-images.githubusercontent.com/855189/62435708-849ba300-b780-11e9-8906-15145ebb9d7a.png)

This issue is therefore to remove the appveyor configuration then?

**Comment by gusmith** [comment]
Hi @MehdiGol 
I can only mentioned what I remember, which is not that much as it happened a few years ago now, but at the time, Azure had really great offers for open source projects to run CI and CD (number of parallel jobs, time to get a worker, etc).
From memory, we found that AppVeyor was quite slow (e.g. https://github.com/data61/clkhash/issues/121) but I do not remember well the details... was it time to get a worker? Was it the worker resources which were a bit small? 
Hoping that help.
