### ISSUE TITLE
Dependencies in requirements.txt and setup.py not in sync

### ISSUE THREAD

**Issue by gusmith** [data61/clkhash#273]
The two files defining the dependencies of the project are not synchronized. 
They already have differences, even some packages being included in one but not in the other. 
It seems the `requirements.txt` is the most up to date (seeing that is where there are more requirements and the latest versions of them).
We should find a way to either have only a single file, or remove one of them if redundant.

**Comment by hardbyte** [comment]
The setup.py is what gets used by users installing clkhash with `pip install` - it should be very forgiving of older dependencies to "play nice" with other libraries requirements. Have a look at https://docs.pipenv.org/en/latest/advanced/#pipfile-vs-setuppy

**Comment by wilko77** [comment]
`setup.py` and `reqirements.txt` serve different purposes.
Whereas `setup.py` defines the minimal viable dependencies, the purpose of the `requirements.txt` file is to achieve _repeatable_ installations for testing and developing purposes. 

This strategy has served us well so far and is in line with best practices. 
Therefore I propose to not change our current process.
