### ISSUE TITLE
CLK upload should include progress

### ISSUE THREAD

**Issue by hardbyte** [data61/clkhash#276]
Possibly helpful links:

- http://blog.iharder.net/2017/03/11/show-upload-progress-with-python-aiohttp-and-tqdm/
- https://2.python-requests.org//en/latest/user/advanced/#streaming-uploads
- https://toolbelt.readthedocs.io/en/latest/uploading-data.html#uploading-data

Might make sense to do as part of #176

**Comment by wilko77** [comment]
upload is now done in anonlink-client. We have a progress bar for uploading to an object store.
