### ISSUE TITLE
Instances similarity computation trouble

### ISSUE THREAD

**Issue by Zar-rok** [data61/clkhash#279]
Hello !

**Description**

I want to use this library to compute similarity between instances of two tables. 

My idea is to create record-level bloom filter for each instances of both tables and then use the [anonlink](https://github.com/data61/anonlink) library to compute the pairwise similarity.

**Problem**

But my problem is that I get a bad similarity score for instances that are similar.
I made the following short example to explain my situation:

The two following tables represent peoples:
* the first one contain two attributes: `first_name` and `last_name`
* the second one contain one attribute: `contactName`

The first table only contain this instance: `{'first_name': 'Jean-Pierre', 'last_name': 'Dupond'}`
The second one: `{'contactName': 'Jean-Pierre Dupond'}`

If I create record-level bloom filter for the two instances and compute the similarity, I should obtain a high percentage. But when I do this, I only get a similarity around _54%_ which seems too low for two similar instances.

**Question**

I've tried to modify the length of the bloom filter or the strategy used to hash each field, but I didn't get better result.

Can you explained why the similarity is low ?
It's linked to the fact that the schemas of the tables are different ?
Do you know what can I do to obtain better results ?

**Information**

I use this script to test: https://github.com/Zar-rok/example/blob/master/example.py.
The `deserialize_bitarray` and `compute_dice_coefficient` functions are extracted from the clkhash [documentation](https://clkhash.readthedocs.io/en/latest/tutorial_api.html#Find-matches-between-the-two-sets-of-CLKs)

I use the following versions: `Python: 3.6.8`, `anonlink: 0.11.2`, `bitarray: 0.9.3`                                                                                                                                                          and `clkhash: 0.13.0`.

Thanks in advance for your help !

Edit: fix anonlink repository's URL

**Comment by hardbyte** [comment]
The issue is very much linked to the fact the schemas are different. Your two tables need to be hashed with the same schema - with the same number of features. Any pre-processing should occur before calling `generate_clks`.

**Comment by Zar-rok** [comment]
So, none of the options related to the schema definition or to the hashing process can make up for the usage of two different schemas ?

**Comment by hardbyte** [comment]
Correct, the data needs to be pre-processed (standardized) before encoding with clkhash.
