### ISSUE TITLE
support for alternative tokenization methods

### ISSUE THREAD

**Issue by wilko77** [data61/clkhash#285]
We currently tokenize every input to n-grams.

However, comparing n-grams is not always the most sensible or desired comparison technique.
For instance, 
- ### exact comparisons
that is, high similarity if values are the same, and low similarity otherwise (even if the values are almost the same).
- ### comparing addresses in the presence of address changes
comparing address strings after an address change leads to arbitrary similarities. An alternative measure is to use the physical distance between addresses as proxy for similarity. (as described in my blog post)
- ### fuzzy integer comparison
the difference between two integer defines the similarity

This is an non-exclusive list.

The linkage schema in its current form does not support alternative tokenization methods. Therefore I propose the following changes to the schema definition:

Similar to ‘strategy’ I propose a new container object to house the different tokenization options. This could be named `tokenization` or `comparison` (The first name is more technical, the second describes better the purpose).
It would look something like this:

```
"features": [
  {
    "identifier": "firstName",
    "format": {
      "type": "string",
      "encoding": "utf-8"
    },
    "hashing": {
      "hash": {"type": "doubleHash"},
      "tokenization": {
        "type": "ngram",
        "n": 2,
        "positional": true
      },
      "strategy": {
        "numBits": 200
      }
    }
  },
  {
    "identifier": "middleNames",
    "format": {
      "type": "string",
      "encoding": "utf-8"
    },
    "hashing": {
      "hash": {"type": "blakeHash"},
      "tokenization": {
        "type": "exact"
      },
      "strategy": {
        "numBits": 200
      }
    }
  },
``` 

The benefit is that we can extend the schema in the future without breaking backwards compatibility.

**Comment by gusmith** [comment]
@wilko77 looking at the latest documentation https://clkhash.readthedocs.io/en/latest/schema.html#example-schema , it seems to be already there with the key `comparison` instead of `tokenization`. I haven't looked at the code, but is the documentation valid? If yes, should we close this issue?

Also wondering, it seems the strategy `k` is valid only for an n-gram tokenization (at least it gives this impression from the documentation https://clkhash.readthedocs.io/en/latest/schema.html#strategy). Is it normal?

**Comment by wilko77** [comment]
Support for alternative tokenization methods was introduced in #286. 
In the schema, a feature description now has a `comparison` object in the `hashing` section. 
For example:
```
{
      "identifier": "DOB YYYY/MM/DD",
      "format": {
        "type": "date",
        "description": "Numbers separated by slashes, in the year, month, day order",
        "format": "%Y/%m/%d"
      },
      "hashing": {
        "comparison": {
          "type": "ngram",
          "n": 1,
          "positional": true
        },
        "strategy": {
          "numBits": 200
        },
        "hash": {"type": "doubleHash"}
      }
    },
```
New methods are implemented by extending the `AbstractComparison` class. See for example #290 where I implemented exact comparison.


> Also wondering, it seems the strategy `k` is valid only for an n-gram tokenization (at least it gives this impression from the documentation https://clkhash.readthedocs.io/en/latest/schema.html#strategy). Is it normal?
Both strategies work with all tokenization/comparison mechanisms. A comparison thing creates a bunch of tokens, and then the strategy defines how those tokens are inserted into the filter. 
I agree though that the docs are somewhat confusing.
