### ISSUE TITLE
tutorial_cli.ipynb test fails on Windows

### ISSUE THREAD

**Issue by gusmith** [data61/clkhash#287]
Not having a Windows machine makes it really hard to debug.
But running the commands
```
python -m pip install -U -r docs/doc-requirements-others.txt
pytest --nbval -x --sanitize-with docs/tutorial_sanitize.cfg docs/tutorial_cli.ipynb
```
fails on Windows machine, returning
```
platform win32 -- Python 3.7.4, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('d:\\a\\1\\s\\.hypothesis\\examples')
rootdir: d:\a\1\s
plugins: hypothesis-4.32.2, nbval-0.9.1, cov-2.7.1, requests-mock-1.6.0
collected 34 items

docs\tutorial_cli.ipynb .......F

================================== FAILURES ===================================
_______________________ docs\tutorial_cli.ipynb::Cell 7 _______________________
Notebook cell execution failed‌
Cell 7: Cell outputs differ‌

Input:
!clkutil hash &quot;PII_a.csv&quot; key1 key2 &quot;_static&#x2F;febrl_schema_v2_overweight.json&quot; &quot;clks_a.json&quot;‌

Traceback:‌
Missing output fields from running code: {&#x27;stdout&#x27;}‌

```

When corrected, update the `.azurePipeline/wholeBuild.yml` file. The step running the tutorial on Windows machine has been commented out (there is a pointer to the issue in comment). this step should work after correction.

**Comment by hardbyte** [comment]
Perhaps as @wilko77 suggested it isn't worth comparing output for notebooks and instead just go back to executing them and checking no cells throw an exception....

**Comment by gusmith** [comment]
The tutorials test are currently commented out from the CI, so I'll close the issue up to the moment we will be able to run them, which is followed bu the issue #321 .
