### ISSUE TITLE
clkhash tests may not need a deployed entity-service on k8s

### ISSUE THREAD

**Issue by gusmith** [data61/clkhash#305]
We often had issues with the deployed entity-service not responding well, taking too long, etc for the tests in clkhash relying on it. A failing test block our whole CI pipeline, so is not convenient.
This issue is first a question to know if we should try another approach. The one I'm thinking of would be to use docker-compose to bring-up an entity-service deployment locally, and use this one for tests, stopping it after. We would be able to pin down a version against which we are testing clkhash.
But other approaches may be better so let's have a thought about it.

**Comment by wilko77** [comment]
clkhash is no longer the home of the rest_client and CLI. This moved to anonlink-client. Thus, this issue is not longer relevant.
