### ISSUE TITLE
Python2 EOL

### ISSUE THREAD

**Issue by hardbyte** [data61/clkhash#307]
> Being the last of the 2.x series, 2.7 will have an extended period of maintenance. Specifically, 2.7 will receive bugfix support until January 1, 2020. After the last release, 2.7 will receive no support.

It's no secret that [Python 2 is reaching its end of life](https://pythonclock.org/). I propose that any clkhash releases after Jan 1 drop support for Python 2.

There is some question of dropping support for Python 3.5 at the same time - giving us access to use  f-strings, ordered dicts with better performance, annotations for typing.

**Comment by wilko77** [comment]
python 2 support was removed in PR #336 
I left python3.5 support for now. How many people still use this?
