### ISSUE TITLE
Testing notebooks on Windows machine in CI

### ISSUE THREAD

**Issue by gusmith** [data61/clkhash#321]
Currently (with master branch), the notebooks cannot install anonlink (which requires a compiler).
When anonlink v0.13 will be released, the issue should be fixed as it will include a windows wheel.

**Comment by hardbyte** [comment]
FYI should be able to test this using the prerelease from PyPi `anonlink==0.13.0.dev0`

**Comment by wilko77** [comment]
anonlink is fine. Now something else fails. See https://dev.azure.com/data61/Anonlink/_build/results?buildId=2506&view=logs&j=556e8606-17d2-50a8-f13f-ecd65b797e53

**Comment by wilko77** [comment]
closed via  #377
